name: Cache

on:
  push:
    paths:
      - 'cache/**'
  pull_request:
    paths:
      - 'cache/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22', '1.23', '1.24']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test cache packages
        run: go test ./cache/...
      - name: Build cache packages
        run: go build ./cache/...
